/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.brianna.catalogo_ventas.v1.Vista;

import java.awt.FlowLayout;

/**
 *
 * @author Usuario
 */
public class CatalogoVista extends javax.swing.JPanel {

    /**
     * Creates new form CatalogoVista
     */
    public CatalogoVista() {
        initComponents();
        galeria1.setLayout(new FlowLayout(FlowLayout.LEFT)); // Establece FlowLayout para galeria1

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollGaleria1 = new javax.swing.JScrollPane();
        galeria1 = new javax.swing.JPanel();
        txtSearchProduct = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(930, 728));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollGaleria1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        galeria1.setBackground(new java.awt.Color(255, 255, 255));
        galeria1.setPreferredSize(new java.awt.Dimension(850, 600));

        javax.swing.GroupLayout galeria1Layout = new javax.swing.GroupLayout(galeria1);
        galeria1.setLayout(galeria1Layout);
        galeria1Layout.setHorizontalGroup(
            galeria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        galeria1Layout.setVerticalGroup(
            galeria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        scrollGaleria1.setViewportView(galeria1);

        add(scrollGaleria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 830, 630));
        add(txtSearchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 250, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel galeria1;
    public javax.swing.JScrollPane scrollGaleria1;
    public javax.swing.JTextField txtSearchProduct;
    // End of variables declaration//GEN-END:variables
}
