/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.brianna.catalogo_ventas.v1.Vista;

/**
 *
 * @author Usuario
 */
public class KARDEXVista extends javax.swing.JPanel {

    /**
     * Creates new form KARDEXVista
     */
    public KARDEXVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDescargarKardex = new javax.swing.JButton();
        txtFiltrarKardex = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKardex = new javax.swing.JTable();
        txtBuscarKardex = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDescargarKardex.setText("Descargar KARDEX");
        jPanel1.add(btnDescargarKardex, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 50));

        txtFiltrarKardex.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFiltrarKardex.setText(": 1000000");
        jPanel1.add(txtFiltrarKardex, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 80, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 370, 900, 350));

        tblKardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKardex);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 75, 900, 290));
        add(txtBuscarKardex, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 200, 40));

        jLabel15.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(98, 91, 113));
        jLabel15.setText("Barra de busqueda");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargarKardex;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKardex;
    private javax.swing.JTextField txtBuscarKardex;
    private javax.swing.JTextField txtFiltrarKardex;
    // End of variables declaration//GEN-END:variables
}
