/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.brianna.catalogo_ventas.v1.Vista;

/**
 *
 * @author Usuario
 */
public class MenuEncargadoVentaVista extends javax.swing.JPanel {

    /**
     * Creates new form MenuEncargadoVenta
     */
    public MenuEncargadoVentaVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnMisVentas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Quicksand Light", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(98, 91, 113));
        jLabel6.setText("Brianna");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnPerfil.setFont(new java.awt.Font("Quicksand Light", 0, 14)); // NOI18N
        btnPerfil.setText("Perfil");
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 60));

        btnCerrarSesion.setFont(new java.awt.Font("Quicksand Light", 0, 14)); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 150, 60));

        btnClientes.setFont(new java.awt.Font("Quicksand Light", 0, 14)); // NOI18N
        btnClientes.setText("Clientes");
        add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 150, 60));

        btnMisVentas.setFont(new java.awt.Font("Quicksand Light", 0, 14)); // NOI18N
        btnMisVentas.setText("Mis ventas");
        add(btnMisVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 150, 60));

        btnReportes.setFont(new java.awt.Font("Quicksand Light", 0, 14)); // NOI18N
        btnReportes.setText("Reportes");
        add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnClientes;
    public javax.swing.JButton btnMisVentas;
    public javax.swing.JButton btnPerfil;
    public javax.swing.JButton btnReportes;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
