
package com.brianna.catalogo_ventas.v1.Vista;


public class MenuEncargadoInventarioVista extends javax.swing.JPanel {

 
    public MenuEncargadoInventarioVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnInicio4 = new javax.swing.JButton();
        btnRegistroProducto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnFacturas2 = new javax.swing.JButton();
        btnFacturas3 = new javax.swing.JButton();
        btnFacturas5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Quicksand Light", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(98, 91, 113));
        jLabel6.setText("Brianna");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnInicio4.setFont(new java.awt.Font("Quicksand Light", 0, 14)); // NOI18N
        btnInicio4.setText("Perfil");
        add(btnInicio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 60));

        btnRegistroProducto.setFont(new java.awt.Font("Quicksand Light", 0, 14)); // NOI18N
        btnRegistroProducto.setText("Registrar producto");
        add(btnRegistroProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 150, 60));

        btnSalir.setFont(new java.awt.Font("Quicksand Light", 0, 14)); // NOI18N
        btnSalir.setText("Cerrar sesión");
        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 150, 60));

        btnFacturas2.setFont(new java.awt.Font("Quicksand Light", 0, 14)); // NOI18N
        btnFacturas2.setText("Kardex");
        add(btnFacturas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 60));

        btnFacturas3.setFont(new java.awt.Font("Quicksand Light", 0, 14)); // NOI18N
        btnFacturas3.setText("Proveedores");
        add(btnFacturas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 150, 60));

        btnFacturas5.setFont(new java.awt.Font("Quicksand Light", 0, 14)); // NOI18N
        btnFacturas5.setText("Consultar producto");
        add(btnFacturas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 150, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnFacturas2;
    public javax.swing.JButton btnFacturas3;
    public javax.swing.JButton btnFacturas5;
    public javax.swing.JButton btnInicio4;
    public javax.swing.JButton btnRegistroProducto;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
