/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.brianna.catalogo_ventas.v1.Vista;

/**
 *
 * @author Usuario
 */
public class RegistroVista extends javax.swing.JPanel {

    /**
     * Creates new form RegistroVista
     */
    public RegistroVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtRegistroNombre = new javax.swing.JTextField();
        txtRegistroDistrito = new javax.swing.JTextField();
        txtRegistroApellido = new javax.swing.JTextField();
        txtRegistroDireccion = new javax.swing.JTextField();
        txtRegistroFechaNacimiento = new javax.swing.JTextField();
        txtRegistroCorreo = new javax.swing.JTextField();
        txtRegistroTelefono = new javax.swing.JTextField();
        txtRegistroUsuario = new javax.swing.JTextField();
        txtRegistroDNI = new javax.swing.JTextField();
        txtRegistroContraseña1 = new javax.swing.JPasswordField();
        txtRegistroRUC = new javax.swing.JTextField();
        txtRegistroContraseña2 = new javax.swing.JPasswordField();
        btnRegistroCuenta = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 728));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(254, 247, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(98, 91, 113));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 43));

        jLabel4.setFont(new java.awt.Font("Quicksand Medium", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(98, 91, 113));
        jLabel4.setText("Registro de cuenta");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        txtRegistroNombre.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroNombre.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroNombre.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroNombre.setText("Ingresar nombre completo");
        add(txtRegistroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 330, 43));

        txtRegistroDistrito.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroDistrito.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroDistrito.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroDistrito.setText("Ingresar distrito");
        txtRegistroDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroDistritoActionPerformed(evt);
            }
        });
        add(txtRegistroDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 330, 43));

        txtRegistroApellido.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroApellido.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroApellido.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroApellido.setText("Ingresar apellido completo");
        txtRegistroApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroApellidoActionPerformed(evt);
            }
        });
        add(txtRegistroApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 330, 43));

        txtRegistroDireccion.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroDireccion.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroDireccion.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroDireccion.setText("Ingresar dirección");
        add(txtRegistroDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 330, 43));

        txtRegistroFechaNacimiento.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroFechaNacimiento.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroFechaNacimiento.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroFechaNacimiento.setText("Ingresar fecha de nacimiento");
        txtRegistroFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroFechaNacimientoActionPerformed(evt);
            }
        });
        add(txtRegistroFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 330, 43));

        txtRegistroCorreo.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroCorreo.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroCorreo.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroCorreo.setText("Ingresar correo electronico");
        add(txtRegistroCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 330, 43));

        txtRegistroTelefono.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroTelefono.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroTelefono.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroTelefono.setText("Ingresar teléfono");
        add(txtRegistroTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 330, 43));

        txtRegistroUsuario.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroUsuario.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroUsuario.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroUsuario.setText("Ingresar nombre de usuario");
        add(txtRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 330, 43));

        txtRegistroDNI.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroDNI.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroDNI.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroDNI.setText("Ingresar DNI");
        txtRegistroDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroDNIActionPerformed(evt);
            }
        });
        add(txtRegistroDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 330, 43));

        txtRegistroContraseña1.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroContraseña1.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroContraseña1.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroContraseña1.setText("Ingresar contraseña");
        txtRegistroContraseña1.setEchoChar('\u0000');
        txtRegistroContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroContraseña1ActionPerformed(evt);
            }
        });
        add(txtRegistroContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 330, 43));

        txtRegistroRUC.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroRUC.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroRUC.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroRUC.setText("Ingresar RUC");
        txtRegistroRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroRUCActionPerformed(evt);
            }
        });
        add(txtRegistroRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 330, 43));

        txtRegistroContraseña2.setBackground(new java.awt.Color(254, 247, 255));
        txtRegistroContraseña2.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        txtRegistroContraseña2.setForeground(new java.awt.Color(91, 91, 91));
        txtRegistroContraseña2.setText("Ingresar nuevamente la contraseña");
        txtRegistroContraseña2.setEchoChar('\u0000');
        txtRegistroContraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroContraseña2ActionPerformed(evt);
            }
        });
        add(txtRegistroContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 330, 43));

        btnRegistroCuenta.setBackground(new java.awt.Color(254, 247, 255));
        btnRegistroCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistroCuenta.setForeground(new java.awt.Color(98, 91, 113));
        btnRegistroCuenta.setText("Registrarse");
        btnRegistroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroCuentaActionPerformed(evt);
            }
        });
        add(btnRegistroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 140, 43));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, -1, 56));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtRegistroDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroDistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroDistritoActionPerformed

    private void txtRegistroApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroApellidoActionPerformed

    private void txtRegistroFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroFechaNacimientoActionPerformed

    private void txtRegistroDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroDNIActionPerformed

    private void txtRegistroContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroContraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroContraseña1ActionPerformed

    private void txtRegistroRUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroRUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroRUCActionPerformed

    private void txtRegistroContraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroContraseña2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroContraseña2ActionPerformed

    private void btnRegistroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistroCuenta;
    public javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField txtRegistroApellido;
    public javax.swing.JPasswordField txtRegistroContraseña1;
    public javax.swing.JPasswordField txtRegistroContraseña2;
    public javax.swing.JTextField txtRegistroCorreo;
    public javax.swing.JTextField txtRegistroDNI;
    public javax.swing.JTextField txtRegistroDireccion;
    public javax.swing.JTextField txtRegistroDistrito;
    public javax.swing.JTextField txtRegistroFechaNacimiento;
    public javax.swing.JTextField txtRegistroNombre;
    public javax.swing.JTextField txtRegistroRUC;
    public javax.swing.JTextField txtRegistroTelefono;
    public javax.swing.JTextField txtRegistroUsuario;
    // End of variables declaration//GEN-END:variables
}
