/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.brianna.catalogo_ventas.v1.Vista;

/**
 *
 * @author Usuario
 */
public class RegistrarProveedorVista extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarProveedorVista
     */
    public RegistrarProveedorVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cbxAlmacenProductos = new javax.swing.JComboBox<>();
        txtIGV = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecioProveedor = new javax.swing.JTextField();
        txtPrecioBase = new javax.swing.JTextField();
        txtPrecioFinal = new javax.swing.JTextField();
        cbxCategoriaProducto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();
        btnRegistrarProducto = new javax.swing.JButton();
        btnActualizarProducto = new javax.swing.JButton();
        ToggleBtnSeleccionarProducto = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(98, 91, 113));
        jLabel15.setText("Barra de busqueda");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, -1));
        add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 200, 40));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 75, 900, 290));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxAlmacenProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxAlmacenProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 200, 40));
        jPanel1.add(txtIGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 200, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 40));
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, 40));
        jPanel1.add(txtPrecioProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 200, 40));
        jPanel1.add(txtPrecioBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 200, 40));
        jPanel1.add(txtPrecioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 200, 40));

        cbxCategoriaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jean", "Casaca" }));
        jPanel1.add(cbxCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 200, 40));

        jLabel5.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(98, 91, 113));
        jLabel5.setText("Fecha de nacimiento");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(98, 91, 113));
        jLabel7.setText("Apellido");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(98, 91, 113));
        jLabel8.setText("Nombre");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(98, 91, 113));
        jLabel9.setText("Precio base");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(98, 91, 113));
        jLabel10.setText("Almacen");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(98, 91, 113));
        jLabel11.setText("Precio final");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(98, 91, 113));
        jLabel12.setText("IGV");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(98, 91, 113));
        jLabel13.setText("Categoria");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        btnEliminarProducto.setText("Eliminar producto");
        jPanel1.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 150, 50));

        btnRegistrarProducto.setText("Registrar producto");
        jPanel1.add(btnRegistrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 150, 50));

        btnActualizarProducto.setText("Actualizar producto");
        jPanel1.add(btnActualizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 150, 50));

        ToggleBtnSeleccionarProducto.setText("Seleccionar producto");
        jPanel1.add(ToggleBtnSeleccionarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 150, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 370, 900, 350));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ToggleBtnSeleccionarProducto;
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JComboBox<String> cbxAlmacenProductos;
    private javax.swing.JComboBox<String> cbxCategoriaProducto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioBase;
    private javax.swing.JTextField txtPrecioFinal;
    private javax.swing.JTextField txtPrecioProveedor;
    // End of variables declaration//GEN-END:variables
}
